CREATE DATABASE chirpy2;
USE chirpy2;

CREATE TABLE `chirps` (

  `id` INT NOT NULL AUTO_INCREMENT,
  `chirp` VARCHAR(140) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);